<?php
/**
 * CLI Config - DO NOT EDIT THIS FILE ON LIVE
 * create a file called: cli.local.php
 *
 * @author Brett O'Donnell <cornernote@gmail.com>
 * @author Zain Ul abidin <zainengineer@gmail.com>
 * @copyright 2013 Brett O'Donnell <cornernote@gmail.com>, Zain Ul abidin <zainengineer@gmail.com>
 * @link https://github.com/cornernote/yii-skeleton
 * @license http://www.gnu.org/copyleft/gpl.html
 */

$config = require(dirname(__FILE__) . '/main.php');

// disable database profiling
$config['components']['db']['enableProfiling'] = false;
$config['components']['db']['enableParamLogging'] = false;

// command map
$config['commandMap']['migrate'] = array(
    'class' => 'system.cli.commands.MigrateCommand',
    'migrationPath' => 'application.migrations',
    'migrationTable' => 'migration',
    'connectionID' => 'db',
    'templateFile' => 'application.migrations.templates.migrate_template',
);
$config['commandMap']['emailSpool'] = 'dressing.commands.EmailSpoolCommand';
$config['commandMap']['errorEmail'] = 'dressing.commands.ErrorEmailCommand';

// local config overrides
if (file_exists(dirname(__FILE__) . '/cli.local.php')) {
    require(dirname(__FILE__) . '/cli.local.php');
}
return $config;