<?php
/**
 * Web Config - DO NOT EDIT THIS FILE ON LIVE
 * create a file called: web.local.php
 *
 * @author Brett O'Donnell <cornernote@gmail.com>
 * @author Zain Ul abidin <zainengineer@gmail.com>
 * @copyright 2013 Mr PHP
 * @link https://github.com/cornernote/yii-skeleton
 * @license http://www.gnu.org/copyleft/gpl.html
 */

$config = require(dirname(__FILE__) . '/main.php');

// web only preloads
$config['preload'][] = 'bootstrap';

// log routes
$config['components']['log']['routes'] = array();
if ($_ENV['_config']['setting']['debug']) {
    // debug, web log route
    $config['components']['log']['routes'][] = array(
        'class' => 'CWebLogRoute',
        'levels' => $_ENV['_config']['setting']['debug_levels'],
        //'levels' => 'trace, info, error, warning, profile',
    );
    if ($_ENV['_config']['setting']['debug_db']) {
        $config['components']['log']['routes'][] = array(
            'class' => 'YdProfileLogRoute',
            'levels' => 'profile',
        );
    }
}
else {
    // no debug, file log route
    $config['components']['log']['routes'][] = array(
        'class' => 'CFileLogRoute',
        'levels' => $_ENV['_config']['setting']['debug_levels'],
    );
}

// assets
$scriptName = dirname($_SERVER['SCRIPT_NAME']);
if ($scriptName == '/') {
    $scriptName = '';
}
$config['components']['assetManager'] = array(
    'class' => 'CAssetManager',
    'basePath' => dirname($_SERVER['SCRIPT_FILENAME']) . DS . 'assets',
    'baseUrl' => $scriptName . '/assets',
);

// themes
if (!empty($_ENV['_config']['setting']['theme'])) {
    $config['theme'] = $_ENV['_config']['setting']['theme'];
}
$config['components']['themeManager'] = array(
    'basePath' => dirname(dirname(__FILE__)) . DS . 'themes',
);

// controller map
$config['controllerMap'] = array(
    'account' => 'dressing.controllers.YdAccountController',
    'attachment' => 'dressing.controllers.YdAttachmentController',
    'audit' => 'dressing.controllers.YdAuditController',
    'auditTrail' => 'dressing.controllers.YdAuditTrailController',
    'contactUs' => 'dressing.controllers.YdContactUsController',
    'emailSpool' => 'dressing.controllers.YdEmailSpoolController',
    'emailTemplate' => 'dressing.controllers.YdEmailTemplateController',
    'error' => 'dressing.controllers.YdErrorController',
    'lookup' => 'dressing.controllers.YdLookupController',
    'menu' => 'dressing.controllers.YdMenuController',
    'role' => 'dressing.controllers.YdRoleController',
    'setting' => 'dressing.controllers.YdSettingController',
    'user' => 'dressing.controllers.YdUserController',
);

// local config overrides
if (file_exists(dirname(__FILE__) . '/web.local.php')) {
    require(dirname(__FILE__) . '/web.local.php');
}
return $config;
